// Single source for app icons: every component imports icons from here,
// never from lucide-react directly (shadcn/ui internals excluded).
export { ListDetails } from "@/components/icons/ListDetails";
export { GoalReplace } from "@/components/icons/GoalReplace";
export { Github } from "@/components/icons/Github";
export { Linkedin } from "@/components/icons/Linkedin";
export {
  BookOpen,
  Briefcase,
  Broom,
  CalendarDays,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Dumbbell,
  GraduationCap,
  Clock,
  Code2,
  Copy,
  ExternalLink,
  Flame,
  Home,
  Heart,
  ImagePlus,
  Infinity,
  Info,
  Languages,
  LayoutGrid,
  LayoutList,
  Lightbulb,
  Link2,
  List,
  ListChecks,
  Loader2,
  LogOut,
  Mail,
  Menu,
  Minus,
  Moon,
  Palette,
  PanelLeft,
  Pause,
  Pencil,
  Plane,
  Play,
  Plus,
  RotateCcw,
  ShieldAlert,
  ShoppingCart,
  Sprout,
  Sun,
  Target,
  Timer,
  Trash2,
  User,
  Utensils,
  Wallet,
  X,
} from "lucide-react";
